services:
  - type: web
    name: anilog
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: anilog-db
          property: connectionString
      - key: JWT_SECRET
        sync: false

  - type: pserv
    name: anilog-db
    plan: free
    ipAllowList: []